---
- name: Check whether flanneld installed or not
  stat: path={{bin_dir}}/flanneld
  register: flanneld_exists

- name: Check whether flanneld package exists or not
  stat: path={{deploy_base}}/{{flanneld_pkg_tgz}}
  register: flanneld_pkg_exists

- name: Get sha256sum of package if exists
  stat: path={{deploy_base}}/{{flanneld_pkg_tgz}} checksum_algorithm=sha256
  register: flanneld_sha256sum
  when: flanneld_pkg_exists.stat.exists == true and flanneld_exists.stat.exists == true

- name: Get flanneld package
  get_url: url={{flanneld_pkg_link}} dest={{deploy_base}}
  when: flanneld_exists.stat.exists == false or (flanneld_exists.stat.exists == true and flanneld_pkg_exists.stat.exists == true and flanneld_sha256sum.stat.checksum != flanneld_pkg_sha256sum)

- name: Create unarhive dest folder
  file: path={{deploy_base}}/{{flanneld_pkg_dir}} state=directory

- name: Unarchive package
  unarchive: src={{deploy_base}}/{{flanneld_pkg_tgz}} dest={{deploy_base}}/{{flanneld_pkg_dir}} remote_src=yes

- name: Install binary files
  copy: src={{deploy_base}}/{{flanneld_pkg_dir}}/{{item}} dest={{bin_dir}}/{{item}} remote_src=yes mode=0755
  with_items:
    - flanneld

- name: Set default config file
  template: src=default.j2 dest={{default_cfg_dir}}/flanneld mode=0644

- name: Set upstart init config file
  template: src=init.j2 dest={{init_cfg_dir}}/flanneld.conf mode=0644

- name: Install init.d file
  template: src=init.d.j2 dest={{initd_dir}}/flanneld mode=0755

- name: Add flanneld to system servie list
  shell: update-rc.d flanneld defaults

- name: Check whether flanneld start or not
  shell: ps -C flanneld --no-headings | wc -l
  register: flanneld_running
  ignore_errors: True

- name: Start flanneld if not running
  service: name=flanneld state=started
  when: flanneld_running.stdout == "0"

- name: Restart flanneld if already running
  service: name=flanneld state=restarted
  when: flanneld_running.stdout != "0"

- name: Install docker init script
  template: src=configDocker.j2 dest=/tmp/configDocker.sh mode=0755

- name: Init flanneld net
  shell: chdir=/tmp ./configDocker.sh
