---
- name: Install TLS bootstrap token file
  template: src=token.csv dest={{k8s_cfg_dir}}

- name: Install kubeconfig prepare script
  template: src=kubeconfigPrepare.sh dest={{k8s_cfg_dir}} mode=0755

- name: Prepare kubeconfig
  shell: chdir={{k8s_cfg_dir}} ./kubeconfigPrepare.sh

- name: Check whether prepared or not
  shell: chdir={{k8s_cfg_dir}} ls -1 | grep -E "bootstrap.kubeconfig|kube-proxy.kubeconfig" | wc -l
  register: cfg_count
  ignore_errors: True

- name: Abort deployment when prepare faild
  fail: msg="{{cfg_count.stdout}}"
  when: cfg_count.stdout !=  "2"

- name: Create folder to save kubeconfig files
  file: path={{share_kubeconfig_dir}} state=directory

- name: Copy kubeconfig files to share folder
  copy: src={{k8s_cfg_dir}}/{{item}} dest={{share_kubeconfig_dir}}/{{item}} remote_src=yes
  with_items:
    - bootstrap.kubeconfig
    - kube-proxy.kubeconfig
